### PR TITLE
Provide rake tasks to make it easier to manage the blog

### PR DESCRIPTION
**Pull request by hashhar**
This pull is a WIP. It will allow people to run commands like:

```
rake new_blog_post title
rake new_news title
rake preview
rake generate
```

### CODE REVIEW

**Comment by kathweaver** [comment]
So how do you run that?

**Comment by hashhar** [comment]
I haven't finished it yet. Will let everyone know when its ready.

**Comment by kathweaver** [comment]
If this isn't finished, why is it a pull request?

**Comment by hashhar** [comment]
I have implemented 4 tasks now. Test them out.

```
rake new_blog_post
rake new_news_item
rake generate
rake preview
```
The `new_blog_post` and `new_news_item` can take arguments too:
```
rake new_blog_post[post-name,author-name]
rake new_news_item[post-name,author-name]
```
Test them out.

**Comment by hashhar** [comment]
You can also request any new tasks if you want.

**Comment by hashhar** [comment]
Has anybody tested this out so far?

**Comment by RobStand** [comment]
@hashhar If you can write up a short tutorial in a comment on this PR, @kathweaver will be able to test the rakefile.

**Comment by hashhar** [comment]
There are the following tasks available.

1. `rake generate`:

    This will generate the website using Jekyll but not run the webserver.
2. `rake preview`:

    Preview the generated website in a browser and keep watching for changes.
3. `rake new_blog_post[title,author,file-extension]`:

    Begin a new blog post in /_posts. Use as `rake new_news_item[title,author,file-extension]`. In absence of any of those, the values will be asked for interactively.
4. `rake new_news_item[title,author,file-extension]`:

    Begin a new news post in /_posts. Use as `rake new_news_item[title,author,file-extension]`. In absence of any of those, the values will be asked for interactively.
5. `rake new_release[version,author,file-extension]`:

    Begin a new release post in /_posts. Use as `rake new_release[version-number,author,file-extension]`. In absence of any of those, the values will be asked for interactively. The fully formed title becomes 'Open Live Writer version-number is now available!'.

**Comment by kathweaver** [comment]
So I still understand when and how the rake is done?

**Comment by hashhar** [comment]
You can simply type `rake name-of-task` when you want to do that task from the command line.
It saves you the additional work of typing out the headers of the files and naming and placing them where they need to be.

**Comment by kathweaver** [comment]
I've downloaded your branch, put it on my computer, went to the directory that the branch is in and typed in 

rake generate 
and got LoadError: cannot load such file -- stringe

rake preview
and got the same.

What am I missing?

**Comment by hashhar** [comment]
@kathweaver My bad. You have to run `bundle install` first.

**Comment by kathweaver** [comment]
bundle install gives me not recognized error

**Comment by kathweaver** [comment]
Okay, I've done 
gem install bundler
bundle install

and still get the same error

**Comment by hashhar** [comment]
Hmmm. I'll look into that. In the meantime try installing http://rubyinstaller.org/downloads/

Run `ruby --version` and install the correct one from the 3 links on the left side.

**Comment by kathweaver** [comment]
I have Ruby on my machine --still getting the same thing.

**Comment by hashhar** [comment]
No, that's the dev kit I pasted the link to. Bundle needs the dev kit to work.

**Comment by hashhar** [comment]
screenshot from 2016-02-22 07-52-10

See the 3 links on the left.

**Comment by kathweaver** [comment]
I already have that installed.  Everything runs but the rake -- it's expected stringex

**Comment by hashhar** [comment]
Hmm. Oh, I get it now. Run `gem install stringex` from a command prompt as an admin. Then try again.

**Comment by kathweaver** [comment]
That did the trick.  Thanks!  Now I have to remember how to pull the branch :-)

**Comment by kathweaver** [comment]
Testing now!

**Comment by kathweaver** [comment]
Everything looks good but:

rake new_release[0.7,kathweaver,html]

I get a title Open Live Writer #version is now available!  and an address of http://127.0.0.1:4000/news/release/2016/02/21/open-live-writer-number-version-is-now-available.html

**Comment by kathweaver** [comment]
Better, but I ran:  

rake new_release[0.70.kathweaver,html]


and got:

Version 0.6 Now Available  

 13 Feb 2016  hashhar

**Comment by hashhar** [comment]
@kathweaver Try again. You might be seeing that 0.6 because it was already there. Try again and run `git status`. That will show you the newly created file in red.

snip_20160222222123

**Comment by kathweaver** [comment]
It's working as expected now.  Not sure what was going on this morning.

**Pull request merged**
