### PR TITLE
Added page to answer how to set up FTP server

### LINKED ISSUE #17: Add page to document how to set up FTP Site
This page will help resolve [Issue 179 FTP help page is missing when you click on "How do I configure FTP site?] https://github.com/OpenLiveWriter/OpenLiveWriter/issues/179 and provide further user documentation.

The OpenLiveWriter link is currently: http://openlivewriter.org/WriterRedirect/WriterFTPHelpV3?Version=0.0&Build=5.0&Market=en-US

The LiveWriter page exists at http://windows.microsoft.com/en-US/windows-live/writer-ftp-server-images-photos-ui

Question: Do we want to use the existing link (Not very description), or create an entirely new page, and link to the new page.

I vote for the software change.

### PR DESCRIPTION
**Pull request by kathweaver**
Retained the prior name of the page and most of the content.

This will resolve #17

### CODE REVIEW

**Comment by RobStand** [comment]
Hi @kathweaver, the Site.html commit is included in this PR as well.

**Comment by kathweaver** [comment]
It shouldn't be.

**Comment by RobStand** [comment]
@kathweaver I don't think we should use the text from the Microsoft page as it is copyrighted. A page with new instructions will need to be written. Also, the site.html doesn't appear to be complete and it has a few issues (spacing between words, capitalization). I'm going to close this PR so that a new page on how to set up an FTP site can be created to satisfy #17. I recommend a complete solution to #20 before submitting a PR.

**Comment by kathweaver** [comment]
Okay, I assumed they had transferred copyright to the webpages along with the source.  We all know about assumed.

**Comment by RobStand** [comment]
It's an honest mistake. :)

**Pull request closed without merging**
