### PR TITLE
[WIP] Isuue #20

### LINKED ISSUE #20: Need site navigation
We really need some basic navigation in the site.  Here are the things I can think of that we'd like to have on the site if we can figure out where to link it all:

 - Front page (Download, elevator pitch and screenshots)
 - News / Blog (it's very ironic that the key offline tool for bloggers doesn't have a blog bloggers can subscribe to)
 - Tutorial
   -  How to get started with the various blog services we support
   -  Inserting images (with accessibility info), inserting video etc
   -  Power features and other options etc
 - Plugin Gallery
 - Getting Involved with the community
    - Bug reports
    - Feature suggestions
    - Developing
    - Localization / Translations
 - Discussions / Forums / Getting Help
 - About the project, some history etc

If anyone feels like having a go at the basic layout of the site to give us a structure for our site navigation then be my guest. I think that would then unblock things like #15 and much more.

### PR DESCRIPTION
**Pull request by hashhar**
This is a branch looking to fix #20.

I have added a navbar. Yet to add links to proper pages.

Planned to make certain Jekyll subpages (tutorial, release notes) using the markdown files available in the main OLW repo.

### CODE REVIEW

**Comment by hashhar** [comment]
This looks like this when rendered.

screenshot 59

**Comment by hashhar** [comment]
Do take notice that the `Blog` link is dead. It currently points to `http://openlivewriter.org/WriterRedirect/WriterBlog` which doesn't exist.

**Comment by kathweaver** [comment]
Didn't you suggest we set up a /_posts/blog

I've put a blog entry there, should that link post to it.

**Comment by kathweaver** [comment]
We should be able to have multiple authors be able to post there.

**Comment by hashhar** [comment]
I'll check it on my end and see how it works and do changes accordingly.

**Comment by kathweaver** [comment]
I ran the setup again, and I get the screen mentioned above.

**Comment by hashhar** [comment]
@rebornix I think for the changes I am proposing, #15 has to be merged first. Because in what I have, I am unable to generate any post page when putting files into `_posts`. I think we have a customized configuration of Jekyll.

**Comment by kathweaver** [comment]
I've seeing that also. :+1:

**Comment by hashhar** [comment]
@martinwoodward I have added a navbar with:

- Logo that redirects to site homepage.
- Link to Homepage
- Link to News page (See #15 )
- Link to non-existent blog (**IS THIS NEEDED**)

Some other links I think are useful (but haven't added yet):
- Tutorials and Guides
 - Setup FTP and other support pages as a drop-down
- **Link to star us?**

**Comment by kathweaver** [comment]
Can this be merged please?  We've got a bug right now in the documentation and we really can't go further on the website until this is merged -- plus the rest of the pull requests.

**Comment by hashhar** [comment]
In the current state the navigation bar has some broken links,

- Blog

And some missing links,

- Tutorials and Guides
- Star/Fork on GitHub

Other than that, everything works as it should.

**Comment by kathweaver** [comment]
So should it be merged?

**Comment by hashhar** [comment]
I think so. Nothing is wrong with it.

**Comment by RobStand** [comment]
Merging this. Test it out and submit PRs if anything is wonky.

**Pull request merged**
