### PR TITLE
Add Gitter Sidecar

### PR DESCRIPTION
**Pull request by gep13**
**NOTE:** I wasn't in a position to test this locally, as I don't have the infrastructure set up to run the Jekyll site, but based on my understanding, this should work.

### CODE REVIEW

**Comment by gep13** [comment]
This was originally suggested here: https://github.com/OpenLiveWriter/OpenLiveWriter/pull/106#issuecomment-164175776

**Comment by RobDolinMS** [comment]
Thanks for submitting this @gep13.  There has been some discussion about Gitter not necessarily being a good fit the OpenLiveWriter.org website since the website faces end-users who may want basic help with Open Live Writer as a blogging client and a chat like Gitter.im associated with GitHub may be a better fit for developers who want to get their hands dirty in code.  Tagging @martinwoodward for his two cents on this.

**Comment by gep13** [comment]
@RobDolin @martinwoodward thanks for getting back to me.  Is the concern the requirement to have a GitHub account in order to join the discussion, or that the content of the discussion might put some people off asking for help?  If the latter, would have two Gitter Rooms make sense?  You could leave the existing one as is, and this would be used for developer centric discussions, and create another one, tied to this repository, which would be the end user focused discussion around actually using the application?

**Comment by martinwoodward** [comment]
The main concern for me is that I want to make sure the Gitter room is a place that developers on Open Live Writer feel they can hang out and ask questions related to the development of open live writer rather than it become an end-user support channel bearing in mind Live Writer has a lot of non-developer users.

I'm not saying we shouldn't have better end-user support channels, I'm definitely up for that - I just would like to try to make sure Gitter is something you want open as a developer on Live Writer while you are thinking about Live Writer so that you can chat and help out other developers like you would if we where all hacking together around a table.

Therefore, having a bit of a bar for discoverability on the Gitter channel isn't a bad thing IMHO and having it in the GitHub ReadMe is a fairly standard place I would go look if I wanted to get more involved with a project as a developer, but I'm very open to being convinced otherwise.

**Comment by gep13** [comment]
@martinwoodward @RobDolin should I close this PR?

**Pull request closed without merging**
