### PR TITLE
Moved Navbar

### PR DESCRIPTION
**Pull request by kathweaver**
Moved Navbar to resolve issue #48

### CODE REVIEW

**Comment by kathweaver** [comment]
It looks like this:

**Comment by kathweaver** [comment]
Note that I've played around with making the background color purple, but it looks constantly better with the white background.

**Comment by hashhar** [comment]
Hmmm, looks good :smile: . I came up with this meanwhile: 
screenshot 261

**Comment by kathweaver** [comment]
I like this version better.  Can you add it to my pull?

**Comment by kathweaver** [comment]
Okay, I see your pull, so I closed this.

**Pull request closed without merging**
